### ISSUE TITLE
having trouble to installing dumb-mp3-streamer

### ISSUE THREAD

**Issue by nirmalkushwah** [ugjka/dumb-mp3-streamer#1]
Hi There,
              I am trying to installing dumb-mp3-streamer to my ubuntu machine, first of all, there is no installation process to follow in the readme, as I am trying to do Make and Make install, but getting an error,
~/dumb-mp3-streamer$ make
GOPATH=/home/nik/dumb-mp3-streamer/deps go get -d github.com/ugjka/dumb-mp3-streamer
/bin/sh: 1: go: not found
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 127

Please help me to get rid of this issue.
You did a great job to combine arecord out to HTTP stream, as its a lightweight tool for me.

**Comment by ugjka** [comment]
> /bin/sh: 1: go: not found

Well, the error message tells what you need. In this case you need the Go compiler. I think it is in package called golang under debian. So you need to install that

There are also precompiled binaries on the releases page

**Comment by nirmalkushwah** [comment]
> > /bin/sh: 1: go: not found
> 
> Well, the error message tells what you need. In this case you need the Go compiler. I think it is in package called golang under debian. So you need to install that
> 
> There are also precompiled binaries on the releases page

Thanks, ugka for your instant replay, now the tool is working fine, the tool is great, I have been searching this tool so long.
Also, it will very help full if you mention the installation steps in readme.md file

**Comment by ugjka** [comment]
Ok, thanks I will mention the installation steps
